AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreateAccountRolesDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Role
          AttributeType: S
        - AttributeName: AccountId
          AttributeType: S
      KeySchema:
        - AttributeName: Role
          KeyType: HASH
        - AttributeName: AccountId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: CrossAccountManager-Account-Roles