AWSTemplateFormatVersion: '2010-09-09'
Description: '(SO0015) - Cross-Account Manager Solution: Master Account template '
Resources:
  CreateAccountRolesDDBTable:
    Properties:
      Type: AWS::DynamoDB::Table
      AttributeDefinitions:
        - AttributeName: Role
          AttributeType: S
        - AttributeName: AccountId
          AttributeType: S
      KeySchema:
        - AttributeName: Role
          KeyType: HASH
        - AttributeName: AccountId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: CrossAccountManager-Account-Roles